ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
#FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}

# New https://github.com/elastic/elasticsearch/tree/master/distribution/docker
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}


# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
